name: Publish

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: MineInAbyss/publish-action@develop
        with:
          maven-metadata-url: https://repo.mineinabyss.com/releases/com/mineinabyss/mineinabyss/maven-metadata.xml
#          pages-path: build/dokka/htmlMultiModule/
#          dokka: dokkaHtmlMultiModule
          maven-username: ${{ secrets.MAVEN_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PASSWORD }}
          release-files: |
            ${{ github.workspace }}/publish/*.jar
